name: Test & Report Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  uploadCodeCov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - name: Setup node (with version from .nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.node_version.outputs.NODE_VERSION }}
      - name: install dev dependencies
        run: yarn install --frozen-lockfile
      - name: install codecov
        run: yarn add --dev codecov
      - name: create coverage report
        run: yarn test --coverage
      - name: upload coverage report to codecov
        run: yarn codecov --token="${{ secrets.CODECOV_TOKEN }}"
